from pyrogram import filters
from pyrogram.types import Message
from pyrogram.errors import ChatAdminRequired, ChatInvalid, PeerIdInvalid, UserNotParticipant, InviteHashInvalid
from AviaxMusic import app
from config import BANNED_USERS

# सिर्फ इस यूजर को अनुमति है
AUTHORIZED_USER = 7168729089

@app.on_message(filters.command("link") & ~BANNED_USERS)
async def get_chat_link(client, message: Message):
    # ✅ 1. केवल ऑथराइज्ड यूजर ही एक्सेस करे
    if message.from_user.id != AUTHORIZED_USER:
        return await message.reply_text("❌ आपको इस कमांड का उपयोग करने की अनुमति नहीं है।", quote=True)

    # ✅ 2. चैट ID चेक करें
    if len(message.command) != 2:
        return await message.reply_text("❌ सही उपयोग: `/link <chat_id>`", quote=True)

    chat_id = message.command[1]

    try:
        # ✅ 3. बोट की मेंबरशिप और परमिशन चेक करें
        bot_member = await app.get_chat_member(chat_id, "me")

        # ✅ 4. एडमिन और इनवाइट लिंक परमिशन चेक
        if bot_member.status != "administrator":
            return await message.reply_text("❌ मैं उस ग्रुप में एडमिन नहीं हूँ।", quote=True)

        if not bot_member.privileges.can_invite_users:
            return await message.reply_text("❌ मेरे पास 'Invite Users via Link' की अनुमति नहीं है।", quote=True)

        # ✅ 5. इनवाइट लिंक प्राप्त करें
        chat = await app.get_chat(chat_id)
        invite_link = chat.invite_link or await app.export_chat_invite_link(chat_id)

        await message.reply_text(
            f"✅ **{chat.title}** का इनवाइट लिंक:\n{invite_link}\n\nGenerated by [ZeeMusicBot](https://t.me/ZeeMusicBot)",
            disable_web_page_preview=True,
            quote=True
        )

    except ChatInvalid:
        await message.reply_text("❌ चैट ID गलत है। कृपया सही ID का उपयोग करें।", quote=True)
    except PeerIdInvalid:
        await message.reply_text("❌ चैट ID का फॉर्मेट गलत है।", quote=True)
    except UserNotParticipant:
        await message.reply_text("❌ मैं उस ग्रुप का सदस्य नहीं हूँ।", quote=True)
    except ChatAdminRequired:
        await message.reply_text("❌ मुझे इनवाइट लिंक प्राप्त करने के लिए एडमिन बनाएं।", quote=True)
    except InviteHashInvalid:
        await message.reply_text("❌ इनवाइट लिंक बनाने में समस्या आई। कृपया पुनः प्रयास करें।", quote=True)
    except Exception as e:
        await message.reply_text(f"❌ एक त्रुटि हुई: `{e}`", quote=True)
